# Generated by Django 5.1.1 on 2025-11-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("required_exp", models.PositiveIntegerField(default=100)),
            ],
            options={
                "ordering": ["required_exp"],
            },
        ),
    ]
