# Generated by Django 5.1.1 on 2025-01-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParkingPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("coords", models.JSONField(default=dict, verbose_name="coordynaty")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Utworzono"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Ostatnia aktualizacja"
                    ),
                ),
            ],
        ),
    ]
