# Generated by Django 5.1.1 on 2025-01-24 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parking_points", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parkingpoint",
            old_name="coords",
            new_name="location",
        ),
    ]
