# Generated by Django 5.1.1 on 2025-12-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_system", "0003_alter_account_groups_alter_account_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
