# Generated by Django 5.1.1 on 2025-12-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_system", "0005_alter_account_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
