# Generated by Django 5.1.1 on 2025-01-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_point", "0002_rename_coords_parkingpoint_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingpoint",
            name="location",
            field=models.JSONField(verbose_name="coordynaty"),
        ),
        migrations.AlterField(
            model_name="parkingpoint",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
