# Generated by Django 5.1.1 on 2025-01-31 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_point", "0003_alter_parkingpoint_location_alter_parkingpoint_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingpoint",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parking_points",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
