# Generated by Django 5.1.1 on 2025-11-29 15:36

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_point", "0004_parkingpoint_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingpoint",
            name="properties",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("camera", "Monitoring"),
                    ("covered", "Zadaszony"),
                    ("ev", "Ładowanie EV"),
                    ("paid", "Płatny"),
                    ("guarded", "Strzeżony"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="parkingpoint",
            name="status",
            field=models.IntegerField(choices=[(0, "Draft"), (1, "Active")], default=0),
        ),
    ]
