# Generated by Django 5.1.1 on 2025-11-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parking_point", "0005_parkingpoint_properties_parkingpoint_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkingpoint",
            name="status",
        ),
    ]
