# Generated by Django 5.1.1 on 2025-11-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_point", "0006_remove_parkingpoint_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingpoint",
            name="occupancy",
            field=models.CharField(
                blank=True,
                choices=[("HIGH", "high"), ("MEDIUM", "medium"), ("LOW", "low")],
                max_length=255,
                null=True,
            ),
        ),
    ]
