# Generated by Django 5.1.1 on 2025-11-30 14:10

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parking_point", "0007_parkingpoint_occupancy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingpoint",
            name="properties",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("camera", "Monitoring"),
                    ("covered", "Zadaszony"),
                    ("ev", "Ładowanie EV"),
                    ("paid", "Płatny"),
                    ("guarded", "Strzeżony"),
                    ("dangerous_district", "niebezpieczny_rejon"),
                ],
                max_length=49,
                null=True,
            ),
        ),
    ]
