# Generated by Django 5.1.1 on 2025-12-02 13:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_point", "0008_alter_parkingpoint_properties"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingpoint",
            name="occupancy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FREE", "Wolne"),
                    ("LIMITED", "Mało miejsc"),
                    ("FULL", "Brak miejsc"),
                    ("UNKNOWN", "Nieznane"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="parkingpoint",
            name="properties",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("DIRTY", "Brudny"),
                        ("FULL", "Przepełniony"),
                        ("DAMAGED", "Uszkodzony"),
                        ("UNSAFE", "Niebezpieczny"),
                        ("OTHER", "Inne"),
                    ],
                    max_length=20,
                ),
                blank=True,
                default=list,
                help_text="Lista właściwości, które użytkownik zgłasza.",
                size=None,
            ),
        ),
    ]
