# Generated by Django 5.1.1 on 2025-12-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parking_point", "0009_alter_parkingpoint_occupancy_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkingpoint",
            name="name",
        ),
    ]
