# Generated by Django 5.1.1 on 2025-12-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_point", "0010_remove_parkingpoint_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkingpoint",
            name="description",
        ),
        migrations.RemoveField(
            model_name="parkingpoint",
            name="occupancy",
        ),
        migrations.RemoveField(
            model_name="parkingpoint",
            name="properties",
        ),
        migrations.AddField(
            model_name="parkingpoint",
            name="has_location_edit_pending",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="parkingpoint",
            name="is_verified",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
