# Generated by Django 5.1.1 on 2025-12-04 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parking_point", "0011_remove_parkingpoint_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parkingpoint",
            old_name="has_location_edit_pending",
            new_name="has_proposal",
        ),
    ]
