# Generated by Django 5.1.1 on 2025-12-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "parking_point",
            "0012_rename_has_location_edit_pending_parkingpoint_has_proposal",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="parkingpoint",
            old_name="has_proposal",
            new_name="has_edit_location_proposal",
        ),
    ]
