# Generated by Django 5.1.1 on 2025-12-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "parking_point",
            "0013_rename_has_proposal_parkingpoint_has_edit_location_proposal",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingpoint",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
