# Generated by Django 5.1.1 on 2026-01-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_point", "0014_alter_parkingpoint_is_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkingpoint",
            name="has_edit_location_proposal",
        ),
        migrations.AddField(
            model_name="parkingpoint",
            name="address",
            field=models.CharField(
                default="unknown", max_length=255, verbose_name="Address"
            ),
            preserve_default=False,
        ),
    ]
