# Generated by Django 5.1.1 on 2026-01-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "parking_point",
            "0015_remove_parkingpoint_has_edit_location_proposal_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkingpoint",
            name="is_verified",
        ),
    ]
