# Generated by Django 5.1.1 on 2026-01-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_point", "0017_alter_parkingpoint_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingpoint",
            name="current_location",
            field=models.JSONField(
                blank=True, null=True, verbose_name="current-location"
            ),
        ),
        migrations.AlterField(
            model_name="parkingpoint",
            name="location",
            field=models.JSONField(verbose_name="original-coordinates"),
        ),
    ]
