# Generated by Django 5.1.1 on 2026-01-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parking_point", "0018_parkingpoint_current_location_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parkingpoint",
            old_name="location",
            new_name="original_location",
        ),
    ]
