# Generated by Django 5.1.1 on 2026-01-09 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parking_point", "0019_rename_location_parkingpoint_original_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parkingpoint",
            old_name="current_location",
            new_name="location",
        ),
    ]
