# Generated by Django 5.1.1 on 2026-01-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_point", "0020_rename_current_location_parkingpoint_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingpoint",
            name="location",
            field=models.JSONField(verbose_name="current-location"),
        ),
    ]
