# Generated by Django 5.1.1 on 2026-01-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_point", "0021_alter_parkingpoint_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingpoint",
            name="marked_for_deletion_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
