# Generated by Django 6.0.2 on 2026-02-22 13:59

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parking_point", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "attributes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("FREE_OFF_SEASON", "Darmowy poza sezonem"),
                                ("DANGEROUS_AREA", "Niebezpieczna okolica"),
                                ("POOR_SURFACE", "Zła nawierzchnia"),
                                ("HARD_ACCESS", "Trudny dostęp"),
                                ("FLOOD_PRONE", "Podatny na podtopienia"),
                                ("POOR_LIGHTING", "Słabe oświetlenie"),
                                ("PARKING_RESTRICTIONS", "Ograniczenia parkingowe"),
                            ],
                            max_length=20,
                        ),
                        blank=True,
                        default=list,
                        help_text="Lista właściwości, które użytkownik zgłasza.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "occupancy",
                    models.CharField(
                        choices=[
                            ("HIGH", "Wysokie"),
                            ("MEDIUM", "Średnie"),
                            ("LOW", "Niskie"),
                            ("NO_SPACE", "Brak miejsca"),
                            ("NO_DATA", "Brak danych"),
                        ],
                        default="NO_DATA",
                        max_length=255,
                    ),
                ),
                ("is_like", models.BooleanField()),
                (
                    "parking_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="parking_point.parkingpoint",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "parking_point")},
            },
        ),
    ]
