# Generated by Django 5.1.1 on 2025-12-02 12:17

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reviews", "0001_initial"),
        ("parking_point", "0008_alter_parkingpoint_properties"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "properties",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("DIRTY", "Brudny"),
                                ("FULL", "Przepełniony"),
                                ("DAMAGED", "Uszkodzony"),
                                ("UNSAFE", "Niebezpieczny"),
                                ("OTHER", "Inne"),
                            ],
                            max_length=20,
                        ),
                        blank=True,
                        default=list,
                        help_text="Lista właściwości, które użytkownik zgłasza.",
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_liked", models.BooleanField(default=False)),
                (
                    "occupancy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FREE", "Wolne"),
                            ("LIMITED", "Mało miejsc"),
                            ("FULL", "Brak miejsc"),
                            ("UNKNOWN", "Nieznane"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "parking_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="parking_point.parkingpoint",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "parking_point")},
            },
        ),
        migrations.DeleteModel(
            name="ParkingPointReport",
        ),
    ]
