# Generated by Django 5.1.1 on 2025-12-02 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reviews", "0003_remove_review_is_liked_reviewvote"),
        ("parking_point", "0010_remove_parkingpoint_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="properties",
            new_name="attribiutes",
        ),
        migrations.AlterField(
            model_name="review",
            name="parking_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reports",
                to="parking_point.parkingpoint",
            ),
        ),
    ]
