# Generated by Django 5.1.1 on 2025-12-03 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reviews", "0004_rename_properties_review_attribiutes_and_more"),
        ("parking_point", "0011_remove_parkingpoint_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="parking_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviews",
                to="parking_point.parkingpoint",
            ),
        ),
        migrations.DeleteModel(
            name="ReviewVote",
        ),
    ]
