# Generated by Django 5.1.1 on 2025-12-06 15:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reviews", "0005_alter_review_parking_point_delete_reviewvote"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_like",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="attribiutes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("FREE_OFF_SEASON", "Darmowy poza sezonem"),
                        ("DANGEROUS_AREA", "Niebezpieczna okolica"),
                        ("POOR_SURFACE", "Zła nawierzchnia"),
                        ("HARD_ACCESS", "Trudny dostęp"),
                        ("FLOOD_PRONE", "Podatny na podtopienia"),
                        ("POOR_LIGHTING", "Słabe oświetlenie"),
                        ("PARKING_RESTRICTIONS", "Ograniczenia parkingowe"),
                        ("OTHERS", "Inne"),
                    ],
                    max_length=20,
                ),
                blank=True,
                default=list,
                help_text="Lista właściwości, które użytkownik zgłasza.",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="occupancy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HIGH", "Wysokie"),
                    ("MEDIUM", "Średnie"),
                    ("LOW", "Niskie"),
                    ("NO_SPACE", "Brak miejsca"),
                    ("NO_DATA", "Brak danych"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
