# Generated by Django 5.1.1 on 2025-12-08 18:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reviews", "0006_review_is_like_alter_review_attribiutes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="attribiutes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("FREE_OFF_SEASON", "Darmowy poza sezonem"),
                        ("DANGEROUS_AREA", "Niebezpieczna okolica"),
                        ("POOR_SURFACE", "Zła nawierzchnia"),
                        ("HARD_ACCESS", "Trudny dostęp"),
                        ("FLOOD_PRONE", "Podatny na podtopienia"),
                        ("POOR_LIGHTING", "Słabe oświetlenie"),
                        ("PARKING_RESTRICTIONS", "Ograniczenia parkingowe"),
                    ],
                    max_length=20,
                ),
                blank=True,
                default=list,
                help_text="Lista właściwości, które użytkownik zgłasza.",
                null=True,
                size=None,
            ),
        ),
    ]
