# Generated by Django 5.1.1 on 2025-12-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reviews", "0007_alter_review_attribiutes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="is_like",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
