# Generated by Django 5.1.1 on 2025-12-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reviews", "0008_alter_review_is_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
