# Generated by Django 5.1.1 on 2025-12-16 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Reviews", "0009_review_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="attribiutes",
            new_name="attributes",
        ),
    ]
