# Generated by Django 5.1.1 on 2025-12-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reviews", "0010_rename_attribiutes_review_attributes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="occupancy",
            field=models.CharField(
                choices=[
                    ("HIGH", "Wysokie"),
                    ("MEDIUM", "Średnie"),
                    ("LOW", "Niskie"),
                    ("NO_SPACE", "Brak miejsca"),
                    ("NO_DATA", "Brak danych"),
                ],
                default="NO_DATA",
                max_length=255,
            ),
        ),
    ]
