# Generated by Django 5.1.1 on 2025-12-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parking_point_edit_location", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="parkingpointeditlocation",
            unique_together=set(),
        ),
    ]
