# Generated by Django 5.1.1 on 2025-12-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "parking_point_edit_location",
            "0002_alter_parkingpointeditlocation_unique_together",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingpointeditlocation",
            name="dislike_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="parkingpointeditlocation",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
