# Generated by Django 5.1.1 on 2025-12-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "parking_point_edit_location",
            "0003_parkingpointeditlocation_dislike_count_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingpointeditlocationvote",
            name="is_like",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
