# Generated by Django 5.1.1 on 2025-12-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "parking_point_edit_location",
            "0004_alter_parkingpointeditlocationvote_is_like",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingpointeditlocation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="parkingpointeditlocationvote",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
