# Generated by Django 5.1.1 on 2026-01-03 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "parking_point_edit_location",
            "0005_parkingpointeditlocation_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="ParkingPointEditLocationVote",
        ),
    ]
