# Generated by Django 5.1.1 on 2026-01-03 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "parking_point",
            "0015_remove_parkingpoint_has_edit_location_proposal_and_more",
        ),
        ("parking_point_edit_location", "0006_delete_parkingpointeditlocationvote"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="parkingpointeditlocation",
            unique_together={("user", "parking_point")},
        ),
        migrations.AlterField(
            model_name="parkingpointeditlocation",
            name="parking_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_edits",
                to="parking_point.parkingpoint",
            ),
        ),
        migrations.RemoveField(
            model_name="parkingpointeditlocation",
            name="dislike_count",
        ),
        migrations.RemoveField(
            model_name="parkingpointeditlocation",
            name="like_count",
        ),
    ]
